apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    app: hw
    interface: rest
    language: golang
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
