apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: todo-rate-limiting
  annotations:
    kubernetes.io/ingress.class: kong
config:
  second: 100
  policy: local
  limit_by: ip
plugin: rate-limiting
