apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cep-rate-limiting
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 50
  policy: local
  limit_by: credential
plugin: rate-limiting
