image:
  repository: kong
  tag: 3.7.1

env:
  prefix: /kong_prefix/
  database: "off"
  plugins: bundled

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    parameters: []
  labels:
    enable-metrics: "true"

postgresql:
  enabled: false

ingressController:
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "3.2"
  enabled: true
  installCRDs: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8100"

proxy:
  type: NodePort

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
